version: "3"

services:
  dockerHook:
    image: waxer59/dockerhook
    container_name: dockerHook
    ports:
      - "8080:8080"
    restart: always
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock